### ISSUE TITLE
suggestion how to add this to the OnlinePackageManager

### ISSUE THREAD

**Issue by Alexey-T** [dioannidis/HIDAPI.pas#4]
- move src file(s) to src\ dir
- create there Lazarus package- LPK file, which includes PAS file and has filled LPK fields
- mail to GetMem at the https://forum.lazarus.freepascal.org/index.php/topic,34297.0.html

**Comment by Alexey-T** [comment]
@dioannidis

**Comment by Alexey-T** [comment]
Using Lazarus dialog 'Package / New package...'.

**Comment by Alexey-T** [comment]
Also, move the demo file(s) to the separate demo/ or demos/maindemo/ dir.

**Comment by dioannidis** [comment]
@Alexey-T 

Is this what it needs to be changed / created for it to be included ?

**Comment by Alexey-T** [comment]
see the 1st message-- yes, you need to create .lpk file.

**Comment by Alexey-T** [comment]
In the 'package hidapi' dialog (in Lazarus), right click the FILES tree node, and do 'add files from file system'.

add the main pas file.

**Comment by Alexey-T** [comment]
![Screenshot from 2022-03-17 21-08-55](https://user-images.githubusercontent.com/4154978/158868079-4d9127f1-e2ad-403b-b959-b20fe8e72aba.png)

**Comment by dioannidis** [comment]
@Alexey-T 

Well, I'm not familiar with Lazarus packages. It seems that I need to read how they work. 

Of course, if you can, I'll appreciate it, if you contribute this via a PR.

**Comment by Alexey-T** [comment]
Made the PR.
