### ISSUE TITLE
add to OnlinePkgManager

### ISSUE THREAD

**Issue by Alexey-T** [dioannidis/HIDAPI.pas#6]
can you please ask at
https://forum.lazarus.freepascal.org/index.php?topic=34297.0
to add the packge to OPM?

**Comment by dioannidis** [comment]
The hidapi_pkg.pas uses the static loading hidapi unit. The dynamic loading is the hidapi_dyn.pas so I'll change it   before adding it to OPM. 
Also, shouldn't I need to create a release and a zip file before asking for inclusion ?

**Comment by Alexey-T** [comment]
1. OK, so change in the IDE Package Manager dialog the included file to _dyn (you can include 2 files too - so Lazarus app will find 2 files)

> I need to create a release and a zip

no

**Comment by dioannidis** [comment]
Hi,

  done . https://forum.lazarus.freepascal.org/index.php/topic,34297.msg437683.html#msg437683
